5calls/ios

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/EditLocationViewController.swift
- FiveCalls/FiveCalls/IssuesContainerViewController.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/Main.storyboard
- FiveCalls/FiveCalls/NotificationNames.swift
* set `IssuesContainerViewController` as `EditLocationViewControllerDelegate` & implemented methods
* dismiss VC on cancel
* set zipcode in UserDefaults on validated zip code entry & post notification
* set locationButton title
* add notification observation in `IssuesViewController` and post fetch with zipcode
Do we care about 9-digit zip codes?
> 5C-ZipLocation

- FiveCalls/FiveCalls/AboutViewController.swift
Most of this existing code wasn’t necessary and it was bugging me so I got rid of the extra stuff and simplified to one UIActivityViewController, which is what a user would probably expect in the first place anyways
> Cleaned up some extraneous code in the AboutViewController for sharing the app.

- FiveCalls/FiveCalls/AboutHtmlViewController.swift
- FiveCalls/FiveCalls/AboutViewController.swift
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/EditLocationViewController.swift
- FiveCalls/FiveCalls/IssueActivityItemSource.swift
- FiveCalls/FiveCalls/IssueDetailViewController.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/MyImpactViewController.swift
- FiveCalls/FiveCalls/StatsPageViewController.swift
- FiveCalls/FiveCalls/WelcomeViewController.swift
Added a bunch of custom actions to log the user behavior across the app.
> Analytics Calls Hooked In

- FiveCalls/FiveCalls/BlueButton.swift
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/ContactLog.swift
This is for issue #47 
I added a new method to ContactLogs to fetch the actual method of contact recorded for a given issue/contact combination, and refactored hasContacted() to use it.
I added colors for the selected state for BlueButtons, and then set the selected state when entering the CallScript controller, based on the recorded method of contact.
> Addresses #47 "Show Checkmark On Call Script Screen" 

- FiveCalls/FiveCallsUITests/FiveCallsUITests.swift
This should fix the problem in build #79
> updated unit tests for latest issues list

- .gitignore
- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Info.plist
- FiveCalls/FiveCallsTests/Info.plist
- FiveCalls/FiveCallsUITests/Info.plist
- Gemfile
- Gemfile.lock
- fastlane/Fastfile
- fastlane/README.md
- automatically increments build number for beta builds and commits this automatically
- badges the app icon with "BETA" and the version number. These changes are reverted afterward.
- tags the version & pushes tags on completion
- pauses while you edit the changelog
- external distribution by default
> Fastlane beta improvments

- FiveCalls/FiveCalls/IssueDetailViewController.swift
Just a couple cell reuse identifiers that got missed.
> Use R.swift when possible

- FiveCalls/FiveCalls/IssuesContainerViewController.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/WelcomeViewController.swift
* Fixed odd UIPageViewController where tapping near the dots got the app into a stuck state. Possibly related to #70. 
* Fixed crash #75 where an odd situation would force unwrap an outlet and cause crash the `IssuesContainerViewController`
* Fixed crash #57 again for sure this time by storing the issues list and not crashing if they change when we reload visible cells for selection changes.
> Three Bug Fixes

- FiveCalls/FiveCalls/AboutViewController.swift
- FiveCalls/FiveCalls/FetchIssuesOperation.swift
> Remove force unwraps from fetch issues op

- FiveCalls/FiveCalls/ContactLog.swift
This is my naive stab at #96; let me know if this doesn't make sense as a place for this revised logic.
> Don’t count “unavailable” as completed.

- FiveCalls/FiveCalls/IssuesManager.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/RemoteImageView.swift
Ran the app under instrumentation a bit and cleaned up the few small memory leaks that I found in code we own.
> Memory Leaks

- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/Info.plist
- FiveCalls/FiveCalls/IssueDetailViewController.swift
- FiveCalls/FiveCalls/IssuesContainerViewController.swift
fixed split view on the iPhone n+
> Fixed i phone 7 plus rotation

- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
> Use standard keyboard for address entry

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/IssueScriptCell.swift
#114 - Editing and scrolling disabled, and I transferred the styling from the previous label; seems to do the trick
> Display script in a UITextView, enabling copying

- FiveCalls/FiveCalls/IssuesViewController.swift
Fix for #159. I went for reloading on every launch because it seemed logically simpler, but if there's a good reason to space it out I can change it.
> Refresh issues outside of just app launch

- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/Base.lproj/Welcome.storyboard
- FiveCalls/FiveCalls/FetchIssuesOperation.swift
- FiveCalls/FiveCalls/IssueDetailViewController.swift
- FiveCalls/FiveCalls/IssuesContainerViewController.swift
- FiveCalls/FiveCalls/IssuesManager.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
Fix for #148 
General approach was to make the issues view controller polymorphic, and then use the table footer view to deal with the transition. Screenshots below.
> Add an option for displaying all issues

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/FetchIssuesOperation.swift
- FiveCalls/FiveCalls/Info.plist
- FiveCalls/FiveCalls/IssueDetailViewController.swift
- FiveCalls/FiveCalls/IssuesManager.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- Storyboard connections for getting from the more issues list -> issue detail weren't set
- Both main and moreissues/inactive issue endpoint needs a location sent to get contacts back
> Fixes issue detail and contacts in more issues

- FiveCalls/FiveCalls/Base.lproj/LaunchScreen.storyboard
- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/Base.lproj/Welcome.storyboard
Fixes #184 
Minor changes mostly, also - I touched the storyboards with a new version of Xcode :)
> Autolayout warnings

- FiveCalls/FiveCalls/IssuesContainerViewController.swift
- circle.yml
> No inset adjustments in ios 11 (to be revised later)

- FiveCalls/FiveCalls/Issue.swift
- FiveCalls/FiveCalls/IssueActivityItemSource.swift
- FiveCalls/FiveCalls/Localizable.strings
Addresses #221:
* Adds `slug` to Issues object
* Changes Share URL to `https://5calls.org/issue/<issue slug>`
* Share now supports Copy to Pasteboard
> #221 - Change Share To Use Slug

- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/IssueScriptCell.swift
* #219 - Fix Share Button Crash
* #217 - Possible fix for weird Crash
> Crash fixes

- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/IssuesViewController.swift
Also swapped the cells to make the entire title show, regardless of how many lines.
Fixes #220
> Adjusted settings to make the cell heights flexible

- FiveCalls/FiveCalls/FetchUserStatsOperation.swift
- FiveCalls/FiveCalls/MyImpactViewController.swift
- FiveCalls/FiveCalls/UserStats.swift
- some tidying up
- fixes a main thread sanitizer error
> My impact tweaks

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/ContactCell.swift
- FiveCalls/FiveCalls/IssueCell.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/ProgressView.swift
Based on jarbogast's work on #196
> Issue #207, add circular progress

- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/UserDefaultsKey.swift
> Don't ask for notifications more than once per month

- FiveCalls/FiveCalls/ScheduleRemindersController.swift
An attempt to improve the day selector's animation. I've tried to make a more smoothly version using Spring Animation and the Core Animation framework instead of using UIView methods.
I thought it would be a good enhancement and it wouldn't take a lot of time to make it. Let me know what you think guys.
I attached two GIFs showing the two version just to make easier for you to compare.
> Improve selector animation to run smoothly

- FiveCalls/FiveCalls/IssueDetailViewController.swift
> Load issue detail header cells even with no contacts

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/Contact.swift
- FiveCalls/FiveCalls/UserLocation.swift
- FiveCalls/FiveCallsTests/ScriptCustomizationTests.swift
Still working on this one, fixes #295
> Script replacement for location and contacts

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/AppDelegate.swift
- FiveCalls/FiveCalls/FiveCalls.entitlements
- FiveCalls/FiveCalls/Issue.swift
- FiveCalls/FiveCalls/IssuesManager.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/IssuesViewModel.swift
- FiveCalls/FiveCalls/UserDefaultsKey.swift
Fixes #35 
Support on the website for this is already complete so you can build this, go to an issue link at 5calls.org and see the automatic "Open in the 5 Calls app" link at the top of Safari. I opted not to make it automatic for now.
Todo:
> Universal link support

- FiveCalls/FiveCalls.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- FiveCalls/FiveCalls/AboutViewController.swift
- FiveCalls/FiveCalls/Base.lproj/About.storyboard
- FiveCalls/FiveCalls/Base.lproj/LaunchScreen.storyboard
- FiveCalls/FiveCalls/Base.lproj/Welcome.storyboard
- FiveCalls/FiveCalls/Info.plist
- FiveCalls/FiveCalls/WelcomeViewController.swift
- FiveCalls/FiveCalls/styles.css
Start to work on Dark Mode - addresses #278.
This touches the Launch, Welcome and About screens.
> Initial dark mode

- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/Colors.xcassets/darkGreenText.colorset/Contents.json
Partly addresses #278 
This uses a different shade for darkGreenText between light and dark mode.
> Dark mode for My Impact screen

- FiveCalls/FiveCalls/IssuesContainerViewController.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
User reported that the progress indicators were not filled after making calls. Turns out this was two issues:
* after Done page when user navigates back to the main list, progress was not showing
* contacts were not loaded on the More list because we already have a list of issues, so progress was not showing
fixes #316
> Fixed a bug where contacts were not loaded on the more page

- .gitignore
- FiveCalls/FiveCalls/AnalyticsManager.swift
- FiveCalls/FiveCalls/AppDelegate.swift
- FiveCalls/FiveCalls/ContactList.swift
- FiveCalls/FiveCalls/DoneCallsViewController.swift
- FiveCalls/FiveCalls/FetchContactsOperation.swift
- FiveCalls/FiveCalls/Localizable.strings
- FiveCalls/FiveCalls/ReportOutcomeOperation.swift
- FiveCalls/FiveCalls/UserDefaultsKey.swift
Create an anonid which can tie together push notifications and call reports. Set the anonid and a generalized district in OneSignal for targeting, and slightly reword the push prompt to better explain our goals.
> Prep for some attribution work

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- FiveCalls/FiveCalls/AboutHtmlViewController.swift
- FiveCalls/FiveCalls/AboutViewController.swift
- FiveCalls/FiveCalls/AnalyticsManager.swift
- FiveCalls/FiveCalls/AppDelegate.swift
- FiveCalls/FiveCalls/Base.lproj/Main.storyboard
- FiveCalls/FiveCalls/CallScriptViewController.swift
- FiveCalls/FiveCalls/DonateCell.swift
- FiveCalls/FiveCalls/DoneCallsViewController.swift
- FiveCalls/FiveCalls/EditLocationViewController.swift
- FiveCalls/FiveCalls/IssueActivityItemSource.swift
- FiveCalls/FiveCalls/IssueDetailViewController.swift
- FiveCalls/FiveCalls/IssuesViewController.swift
- FiveCalls/FiveCalls/ScheduleRemindersController.swift
Another step closer to no firebase. My first attempt at a swift package too.
> Add some pages to plausible and move some old analytics out of the way

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- FiveCalls/FiveCalls/AnalyticsManager.swift
Just some clean up of the project and the analytics code.
> Post plausible clean up

- FiveCalls/FiveCalls/AnalyticsManager.swift
`DEBUG` flag hid a compiler error for this one :)
> Combine properties so the compiler is happy

- FiveCalls/FiveCalls/IssueSplitView.swift
- FiveCalls/FiveCalls/Localizable.strings
> Improved placeholder for issue detail

- FiveCalls/FiveCalls/Dashboard.swift
- FiveCalls/FiveCalls/FetchIssuesOperation.swift
Small change to how category view models are generated for the default list, this keeps the order of the json list.
Fixes #362 
~@cselin one other thing I was trying to accomplish here was scrolling to the top of the list when "more" or "less" is tapped. It doesn't seem like List has any way to set the scroll position, so I was considering moving to ScrollView and ForEach, then manually building a selection state for iPad. Happy to do that but I wanted to check if you can think of an easier way to accomplish the same thing~
> Issue list improvements

- FiveCalls/FiveCalls/Actions.swift
- FiveCalls/FiveCalls/AppDelegate.swift
- FiveCalls/FiveCalls/AppState.swift
- FiveCalls/FiveCalls/Contact.swift
- FiveCalls/FiveCalls/ContactCircle.swift
- FiveCalls/FiveCalls/ContactListItem.swift
- FiveCalls/FiveCalls/IssueDetail.swift
- FiveCalls/FiveCalls/IssueListItem.swift
- FiveCalls/FiveCalls/Middleware.swift
- FiveCalls/FiveCalls/PreviewContacts.swift
- FiveCalls/FiveCalls/Store.swift
- FiveCalls/FiveCalls/UserDefaultsKey.swift
> Create an issue completion cache, show which calls have been made

- FiveCalls/FiveCalls/IssueContactDetail.swift
- FiveCalls/FiveCalls/IssueDetail.swift
- FiveCalls/FiveCalls/IssueNavigationHeader.swift
- FiveCalls/FiveCalls/Localizable.strings
Does what it says on the tin
Fixes #366
> Add share link to issue nav

- FiveCalls/FiveCalls/IssueDone.swift
- FiveCalls/FiveCalls/Welcome.swift
Move the button background inside the button so it's tappable anywhere, not just on the text.
Fixes #382
> Make welcome button tappable anywhere

- FiveCalls/FiveCalls/AboutListItem.swift
- FiveCalls/FiveCalls/AboutSheet.swift
- FiveCalls/FiveCalls/Localizable.strings
* Updated font colors to work for contrast and dark mode, use asset colors
* Each whole row of list is one big touch area, one VoiceOver section
* Updated text portions to resize with dynamic text and not get cut off
> About section accessibility pass

- FiveCalls/FiveCalls/AboutListItem.swift
- FiveCalls/FiveCalls/Colors.xcassets/fivecallsLightBG.colorset/Contents.json
- FiveCalls/FiveCalls/Colors.xcassets/fivecallsRed.colorset/Contents.json
- FiveCalls/FiveCalls/Colors.xcassets/fivecallsRedText.colorset/Contents.json
- FiveCalls/FiveCalls/Info.plist
- FiveCalls/FiveCalls/IssueDetail.swift
- FiveCalls/FiveCalls/MultipleDayPicker.swift
- FiveCalls/FiveCalls/ScheduleReminders.swift
- FiveCalls/FiveCalls/YourImpact.swift
@nickoneill I did a quick spike on the status of dark mode for SwiftUI and it's looking pretty good. I made a few quick changes to get something decent, but we probably want to add official dark appearance colors for custom colors. Let me know what you think!
|About|My Impact|
|-|-|
|![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-03 at 13 58 07](https://github.com/5calls/ios/assets/810263/06d84179-31a7-4c42-b54f-a2de05035c90)|![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-03 at 13 58 03](https://github.com/5calls/ios/assets/810263/e37bd08b-787d-4622-af97-2872536d4045)|
|Reminders|Location|
|-|-|
|![Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-11-03 at 13 57 …
> Support Dark Mode

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Contact.swift
- FiveCalls/FiveCalls/Issue.swift
- FiveCalls/FiveCalls/IssueContactDetail.swift
- FiveCalls/FiveCalls/ScriptReplacements.swift
- FiveCalls/FiveCalls/UserLocation.swift
- FiveCalls/FiveCallsTests/ScriptCustomizationTests.swift
Added script replacements for contact and location to contact detail page, and updated the tests since they're no longer on the Contact or Issue object.
Fixes #391
> Updated script replacements and tests

- FiveCalls/FiveCalls/IssueListItem.swift
- FiveCalls/FiveCalls/Localizable.strings
- FiveCalls/FiveCalls/LocationSheet.swift
Some leftover items that were not localized.
Fixes #395
> Leftover localizations

- FiveCalls/FiveCalls/Contact.swift
- FiveCalls/FiveCalls/Localizable.strings
- FiveCalls/FiveCalls/PreviewContacts.swift
- FiveCalls/FiveCalls/ScriptReplacements.swift
- FiveCalls/FiveCallsTests/ScriptCustomizationTests.swift
Migrates script customization to use Swift Regex as well as cleaned up some more localized strings.
> Use swift regex for script customization

- FiveCalls/FiveCalls/ScriptReplacements.swift
- FiveCalls/FiveCallsTests/ScriptCustomizationTests.swift
|Before|After|
|-|-|
|![Simulator Screenshot - iPhone 15 - 2023-12-20 at 13 23 45](https://github.com/5calls/ios/assets/810263/1fbf74bf-a363-4078-a010-18393ee6f602)|![Simulator Screenshot - iPhone 15 - 2023-12-20 at 13 23 13](https://github.com/5calls/ios/assets/810263/2c60f80a-e802-499b-8910-eac73cefea60)|
|![Simulator Screenshot - iPhone 15 - 2023-12-20 at 13 23 47](https://github.com/5calls/ios/assets/810263/97e8288a-a7aa-40f3-b56c-6f488dd60046)|![Simulator Screenshot - iPhone 15 - 2023-12-20 at 13 23 16](https://github.com/5calls/ios/assets/810263/3fa79753-fe58-4763-ab5c-43ae042a75dd)|
> Shorten script for contact

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- FiveCalls/FiveCalls/AboutListItem.swift
- FiveCalls/FiveCalls/AboutSheet.swift
- FiveCalls/FiveCalls/AcknowListView.swift
- FiveCalls/FiveCalls/Localizable.strings
https://github.com/5calls/ios/assets/810263/1898eecd-49ab-4d29-b82f-80c003a578d3
> Add open source acknowledgements

- FiveCalls/FiveCalls/AppDelegate.swift
- FiveCalls/FiveCalls/Dashboard.swift
- FiveCalls/FiveCalls/FetchUserStatsOperation.swift
- FiveCalls/FiveCalls/IssueListItem.swift
- FiveCalls/FiveCalls/ScriptReplacements.swift
Tightened list spacing on the dashboard, set adaptive color for list separator, fixed a broken Xcode preview, removed a couple warnings
> Misc cleanup

- FiveCalls/FiveCalls/Dashboard.swift
https://github.com/5calls/ios/assets/810263/4f1097ac-fee5-49a2-b519-bba05aff41ac
> Add delay for iOS 17+ to avoid race between popover tip and location sheet

- FiveCalls/FiveCalls/ContactListItem.swift
- FiveCalls/FiveCalls/IssueDetail.swift
Adds (hidden) shortcuts to contacts in the issue detail screen.
Fixes #433
> Add shortcuts to next contacts in issue detail

- FiveCalls/FiveCalls/App.swift
- FiveCalls/FiveCalls/AppState.swift
- FiveCalls/FiveCalls/Dashboard.swift
- FiveCalls/FiveCalls/Store.swift
Moves issue refresh to scene phase changes and out of the dashboard component (@cselin will like this), and tests when the app comes back to foreground.
Fixes #444, maybe will resolve #447 if the cause is something weird about `onAppear` not firing?
> Refresh issues when they haven't been fetched in an hour

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Dashboard.swift
- FiveCalls/FiveCalls/Localizable.strings
- FiveCalls/FiveCalls/NewsletterSignup.swift
Adds a little newsletter signup dingus where folks can add their email for the newsletter.
Fixes #454
> Add a newsletter signup component

- FiveCalls/FiveCalls/AboutSheet.swift
- FiveCalls/FiveCalls/Localizable.strings
Removed twitter and added our usual; insta, bluesky, threads and mastodon
> Added improved social links

- FiveCalls/FiveCalls/LogSearchOperation.swift
Flagged as an error by Xcode, a trivial change
> rename let to var

- FiveCalls/FiveCalls.xcodeproj/project.pbxproj
- FiveCalls/FiveCalls/Actions.swift
- FiveCalls/FiveCalls/AppState.swift
- FiveCalls/FiveCalls/ContactList.swift
- FiveCalls/FiveCalls/FetchContactsOperation.swift
- FiveCalls/FiveCalls/IssueContactDetail.swift
- FiveCalls/FiveCalls/IssueDetail.swift
- FiveCalls/FiveCalls/Middleware.swift
- FiveCalls/FiveCalls/Store.swift
- FiveCalls/FiveCallsTests/IssueDetailWarningTests.swift
- FiveCalls/FiveCallsTests/StoreTests.swift
Added some tests too (or Claude did, at least)
> Provide a warning when looking at state reps with low accuracy location
